// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ssdlFailClass': string;
  'ssdlFailClass2': string;
  'ssdlFailClass3': string;
  'ssdlInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
